{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "micelio.fullname" . }}
  labels:
    {{- include "micelio.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "micelio.selectorLabels" . | nindent 6 }}
      micelio.tuist.dev/surface: admin
  endpoints:
    - port: admin
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
